export { UniversityHero } from './UniversityHero'
export { UniversityPainPoints } from './UniversityPainPoints'
export { DashboardShowcase } from './DashboardShowcase'
export { UniversityAdvantages } from './UniversityAdvantages'
export { UniversityFooter } from './UniversityFooter'
